/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

/**
 *
 * @author likendero
 */
public class PanelTitulo extends javax.swing.JPanel {

    /**
     * Creates new form PanelTitulo
     */
    public PanelTitulo() {
        initComponents();
    }

    @Override
	public void paint(Graphics g) {
		super.paint(g);
		//Graphics2D g2d = (Graphics2D) g;
		
		g.setFont(new Font("Khmer OS System",Font.PLAIN,40));
		g.setColor(Color.CYAN);
		g.drawString("HOTEL Rives*******", 50, 50);
	}
	
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
