/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examennetbeansjaviergonzalezrives;

/**
 *
 * @author likendero
 */
public class PanelContenedor extends javax.swing.JPanel {

    /**
     * Creates new form PanelContenedor
     */
    public PanelContenedor() {
        initComponents();
    }

    public PanelCoches getPanelCoches1() {
        return panelCoches1;
    }

    public void setPanelCoches1(PanelCoches panelCoches1) {
        this.panelCoches1 = panelCoches1;
    }

    public PanelOtrosElementos getPanelOtrosElementos1() {
        return panelOtrosElementos1;
    }

    public void setPanelOtrosElementos1(PanelOtrosElementos panelOtrosElementos1) {
        this.panelOtrosElementos1 = panelOtrosElementos1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCoches1 = new examennetbeansjaviergonzalezrives.PanelCoches();
        panelOtrosElementos1 = new examennetbeansjaviergonzalezrives.PanelOtrosElementos();

        setName("Form"); // NOI18N

        panelCoches1.setName("panelCoches1"); // NOI18N

        panelOtrosElementos1.setName("panelOtrosElementos1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCoches1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOtrosElementos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOtrosElementos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCoches1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private examennetbeansjaviergonzalezrives.PanelCoches panelCoches1;
    private examennetbeansjaviergonzalezrives.PanelOtrosElementos panelOtrosElementos1;
    // End of variables declaration//GEN-END:variables
}
