/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examennetbeansjaviergonzalezrives;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author likendero
 */
public class PanelOtrosElementos extends javax.swing.JPanel {

    /**
     * Creates new form PanelOtrosElementos
     */
    public PanelOtrosElementos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txProv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txprecioCoste = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txPvp = new javax.swing.JTextField();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(examennetbeansjaviergonzalezrives.EXAMENnetbeansJavierGonzalezRivesApp.class).getContext().getResourceMap(PanelOtrosElementos.class);
        setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("Form.border.title"))); // NOI18N
        setName("Form"); // NOI18N

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());
        jSpinner1.setName("jSpinner1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        txProv.setColumns(10);
        txProv.setText(resourceMap.getString("txProv.text")); // NOI18N
        txProv.setName("txProv"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        txTelefono.setColumns(10);
        txTelefono.setText(resourceMap.getString("txTelefono.text")); // NOI18N
        txTelefono.setName("txTelefono"); // NOI18N
        txTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTelefonoActionPerformed(evt);
            }
        });
        txTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txTelefonoKeyPressed(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        txprecioCoste.setColumns(10);
        txprecioCoste.setText(resourceMap.getString("txprecioCoste.text")); // NOI18N
        txprecioCoste.setName("txprecioCoste"); // NOI18N
        txprecioCoste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txprecioCosteKeyPressed(evt);
            }
        });

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        txPvp.setColumns(10);
        txPvp.setText(resourceMap.getString("txPvp.text")); // NOI18N
        txPvp.setName("txPvp"); // NOI18N
        txPvp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txPvpKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txprecioCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txPvp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txprecioCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txPvp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTelefonoActionPerformed

    private void txTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTelefonoKeyPressed
        numericos(evt);
    }//GEN-LAST:event_txTelefonoKeyPressed

    private void txprecioCosteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txprecioCosteKeyPressed
        numericos(evt);
    }//GEN-LAST:event_txprecioCosteKeyPressed

    private void txPvpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPvpKeyPressed
        numericos(evt);
    }//GEN-LAST:event_txPvpKeyPressed
    private void numericos(KeyEvent evt){
        // control que no se pulse algo que no sea un numero
        if(evt.getKeyChar() < '0' || evt.getKeyChar() > '9' && evt.getKeyChar() != '\b'){
          
       }else{ evt.consume();}
    }
    /**
     * metodo que comprueba el estado de los recuadros
     * @return 
     */
    public boolean comprobar(){
        if(
                txProv.getText().isEmpty() ||
                txPvp.getText().isEmpty() ||
                txTelefono.getText().isEmpty() ||
                txprecioCoste.getText().isEmpty()
                ){
            return false;
        }
        // por si acaso el valor numerico
        try{
            if(Integer.parseInt(txPvp.getText()) > 50000){
                JOptionPane.showMessageDialog(this, "no se pueden poner valores tan grandes","error",JOptionPane.ERROR_MESSAGE);
                return false;
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "solo valen datos numericos","error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField txProv;
    private javax.swing.JTextField txPvp;
    private javax.swing.JTextField txTelefono;
    private javax.swing.JTextField txprecioCoste;
    // End of variables declaration//GEN-END:variables
}
