/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panelconlista;

import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Javier Gonzalez Rives
 */
public class ListaConDescripcion extends javax.swing.JPanel {

    /**
     * Creates new form ListaConDescripcion
     */
    public ListaConDescripcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbComidas = new javax.swing.JComboBox();
        lbDescripcion = new javax.swing.JLabel();

        cbComidas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hamburguesa", "Pizza", "Tapas" }));
        cbComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbComidasActionPerformed(evt);
            }
        });

        lbDescripcion.setText("deliciosa carne de vacuno cerdo o mixta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescripcion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cbComidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbDescripcion)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbComidasActionPerformed
        // selector del texto segun elemento
        switch(cbComidas.getSelectedIndex()){
            case 0:
                lbDescripcion.setText("deliciosa carne de vacuno cerdo o mixta");
                break;
            case 1:
                lbDescripcion.setText("masa y queso mozzarela con cosas ricas");
                break;
            case 2:
                lbDescripcion.setText("Forma de comer muy variada y marchosa");
                break;
        }
    }//GEN-LAST:event_cbComidasActionPerformed
// GETTERS SETTERS //////////////////////////////////////////////////////////////
    public JComboBox getCbComidas() {
        return cbComidas;
    }

    public void setCbComidas(JComboBox cbComidas) {
        this.cbComidas = cbComidas;
    }

    public JLabel getLbDescripcion() {
        return lbDescripcion;
    }

    public void setLbDescripcion(JLabel lbDescripcion) {
        this.lbDescripcion = lbDescripcion;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbComidas;
    private javax.swing.JLabel lbDescripcion;
    // End of variables declaration//GEN-END:variables
}
