/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JMenuItem;

/**
 *
 * @author Javier Gonzalez Rives
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miProductos = new javax.swing.JMenuItem();
        miVehiculos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miInforme1 = new javax.swing.JMenuItem();
        miInforme2 = new javax.swing.JMenuItem();
        miInforme3 = new javax.swing.JMenuItem();
        miInforme4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miAcerca = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miAyuda = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jMenu1.setText("file");

        miProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        miProductos.setText("productos");
        miProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductosActionPerformed(evt);
            }
        });
        jMenu1.add(miProductos);

        miVehiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        miVehiculos.setText("vehiculos");
        jMenu1.add(miVehiculos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("reports");

        miInforme1.setText("informe 1, Producto1");
        miInforme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInforme1ActionPerformed(evt);
            }
        });
        jMenu2.add(miInforme1);

        miInforme2.setText("informe 2, productos por comercial");
        jMenu2.add(miInforme2);

        miInforme3.setText("informe 3, comerciales por departamento");
        miInforme3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInforme3ActionPerformed(evt);
            }
        });
        jMenu2.add(miInforme3);

        miInforme4.setText("informe 4, comerciales de un departamento");
        miInforme4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInforme4ActionPerformed(evt);
            }
        });
        jMenu2.add(miInforme4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("about");

        miAcerca.setText("acerca de");
        miAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAcercaActionPerformed(evt);
            }
        });
        jMenu3.add(miAcerca);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("ayuda");

        miAyuda.setText("ayuda");
        miAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAyudaActionPerformed(evt);
            }
        });
        jMenu4.add(miAyuda);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miProductosActionPerformed

    private void miAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAcercaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAcercaActionPerformed

    private void miInforme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInforme1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miInforme1ActionPerformed

    private void miInforme3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInforme3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miInforme3ActionPerformed

    private void miInforme4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInforme4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miInforme4ActionPerformed

    private void miAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAyudaActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem miAcerca;
    private javax.swing.JMenuItem miAyuda;
    private javax.swing.JMenuItem miInforme1;
    private javax.swing.JMenuItem miInforme2;
    private javax.swing.JMenuItem miInforme3;
    private javax.swing.JMenuItem miInforme4;
    private javax.swing.JMenuItem miProductos;
    private javax.swing.JMenuItem miVehiculos;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getMiProductos() {
        return miProductos;
    }

    public void setMiProductos(JMenuItem miProductos) {
        this.miProductos = miProductos;
    }

    public JMenuItem getMiVehiculos() {
        return miVehiculos;
    }

    public void setMiVehiculos(JMenuItem miVehiculos) {
        this.miVehiculos = miVehiculos;
    }

    public JMenuItem getMiAcerca() {
        return miAcerca;
    }

    public void setMiAcerca(JMenuItem miAcerca) {
        this.miAcerca = miAcerca;
    }

    public JMenuItem getMiInforme1() {
        return miInforme1;
    }

    public void setMiInforme1(JMenuItem miInforme1) {
        this.miInforme1 = miInforme1;
    }

    public JMenuItem getMiInforme2() {
        return miInforme2;
    }

    public void setMiInforme2(JMenuItem miInforme2) {
        this.miInforme2 = miInforme2;
    }

    public JMenuItem getMiInforme3() {
        return miInforme3;
    }

    public void setMiInforme3(JMenuItem miInforme3) {
        this.miInforme3 = miInforme3;
    }

    public JMenuItem getMiInforme4() {
        return miInforme4;
    }

    public void setMiInforme4(JMenuItem miInforme4) {
        this.miInforme4 = miInforme4;
    }

    public JMenuItem getMiAyuda() {
        return miAyuda;
    }

    public void setMiAyuda(JMenuItem miAyuda) {
        this.miAyuda = miAyuda;
    }
    
}
