/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;

/**
 *
 * @author Javier Gonzalez Rives
 */
public class InformesDialog extends javax.swing.JDialog {

    /**
     * Creates new form InformesDialog
     */
    public InformesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btInforme1 = new javax.swing.JButton();
        btInforme2 = new javax.swing.JButton();
        btInforme3 = new javax.swing.JButton();
        btInforme4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btInforme1.setText("ver Informe1");

        btInforme2.setText("ver Informe2");

        btInforme3.setText("ver Informe3");

        btInforme4.setText("ver Informe4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btInforme1)
                        .addGap(18, 18, 18)
                        .addComponent(btInforme2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btInforme3)
                        .addGap(18, 18, 18)
                        .addComponent(btInforme4)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInforme1)
                    .addComponent(btInforme2))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInforme3)
                    .addComponent(btInforme4))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInforme1;
    private javax.swing.JButton btInforme2;
    private javax.swing.JButton btInforme3;
    private javax.swing.JButton btInforme4;
    // End of variables declaration//GEN-END:variables

    public JButton getBtInforme1() {
        return btInforme1;
    }

    public void setBtInforme1(JButton btInforme1) {
        this.btInforme1 = btInforme1;
    }

    public JButton getBtInforme2() {
        return btInforme2;
    }

    public void setBtInforme2(JButton btInforme2) {
        this.btInforme2 = btInforme2;
    }

    public JButton getBtInforme3() {
        return btInforme3;
    }

    public void setBtInforme3(JButton btInforme3) {
        this.btInforme3 = btInforme3;
    }

    public JButton getBtInforme4() {
        return btInforme4;
    }

    public void setBtInforme4(JButton btInforme4) {
        this.btInforme4 = btInforme4;
    }


}
