package ies.entity;
// Generated 11-ene-2019 10:58:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int dni;
     private String nombre;
     private Byte edad;
     private Boolean beca;
     private Set matriculas = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(int dni) {
        this.dni = dni;
    }
    public Alumno(int dni, String nombre, Byte edad, Boolean beca, Set matriculas) {
       this.dni = dni;
       this.nombre = nombre;
       this.edad = edad;
       this.beca = beca;
       this.matriculas = matriculas;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Byte getEdad() {
        return this.edad;
    }
    
    public void setEdad(Byte edad) {
        this.edad = edad;
    }
    public Boolean getBeca() {
        return this.beca;
    }
    
    public void setBeca(Boolean beca) {
        this.beca = beca;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


