package ies.entity;
// Generated 11-ene-2019 10:58:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private MatriculaId id;
     private Alumno alumno;
     private Modulo modulo;
     private Date fechaM;
     private Byte convocatoria;
     private Byte notaF;

    public Matricula() {
    }

	
    public Matricula(MatriculaId id, Alumno alumno, Modulo modulo) {
        this.id = id;
        this.alumno = alumno;
        this.modulo = modulo;
    }
    public Matricula(MatriculaId id, Alumno alumno, Modulo modulo, Date fechaM, Byte convocatoria, Byte notaF) {
       this.id = id;
       this.alumno = alumno;
       this.modulo = modulo;
       this.fechaM = fechaM;
       this.convocatoria = convocatoria;
       this.notaF = notaF;
    }
   
    public MatriculaId getId() {
        return this.id;
    }
    
    public void setId(MatriculaId id) {
        this.id = id;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public Date getFechaM() {
        return this.fechaM;
    }
    
    public void setFechaM(Date fechaM) {
        this.fechaM = fechaM;
    }
    public Byte getConvocatoria() {
        return this.convocatoria;
    }
    
    public void setConvocatoria(Byte convocatoria) {
        this.convocatoria = convocatoria;
    }
    public Byte getNotaF() {
        return this.notaF;
    }
    
    public void setNotaF(Byte notaF) {
        this.notaF = notaF;
    }




}


