package ies.entity;
// Generated 11-ene-2019 10:58:57 by Hibernate Tools 4.3.1



/**
 * MatriculaId generated by hbm2java
 */
public class MatriculaId  implements java.io.Serializable {


     private int dni;
     private int mod;

    public MatriculaId() {
    }

    public MatriculaId(int dni, int mod) {
       this.dni = dni;
       this.mod = mod;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public int getMod() {
        return this.mod;
    }
    
    public void setMod(int mod) {
        this.mod = mod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculaId) ) return false;
		 MatriculaId castOther = ( MatriculaId ) other; 
         
		 return (this.getDni()==castOther.getDni())
 && (this.getMod()==castOther.getMod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDni();
         result = 37 * result + this.getMod();
         return result;
   }   


}


