/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semaforo;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author Javier Gonzalez Rives
 */
public class Semaforo extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Semaforo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdrojo = new javax.swing.JRadioButton();
        rdamarillo = new javax.swing.JRadioButton();
        rdverde = new javax.swing.JRadioButton();
        lbtitulo = new javax.swing.JLabel();
        pn = new javax.swing.JPanel();

        buttonGroup1.add(rdrojo);
        rdrojo.setForeground(new java.awt.Color(255, 0, 0));
        rdrojo.setText("ROJO");
        rdrojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdrojoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdamarillo);
        rdamarillo.setForeground(new java.awt.Color(255, 255, 0));
        rdamarillo.setText("AMARILLO");
        rdamarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdamarilloActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdverde);
        rdverde.setForeground(new java.awt.Color(0, 153, 153));
        rdverde.setText("VERDE");
        rdverde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdverdeActionPerformed(evt);
            }
        });

        lbtitulo.setText("SEMAFORO JUAS JUAS");

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdverde)
                            .addComponent(rdamarillo)
                            .addComponent(rdrojo))
                        .addGap(52, 52, 52)
                        .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbtitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(rdrojo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdamarillo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdverde))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdrojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdrojoActionPerformed
        pn.setBackground(Color.RED);
    }//GEN-LAST:event_rdrojoActionPerformed

    private void rdamarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdamarilloActionPerformed
        pn.setBackground(Color.YELLOW);
    }//GEN-LAST:event_rdamarilloActionPerformed

    private void rdverdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdverdeActionPerformed
        pn.setBackground(Color.BLUE);
    }//GEN-LAST:event_rdverdeActionPerformed

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JRadioButton getRdamarillo() {
        return rdamarillo;
    }

    public void setRdamarillo(JRadioButton rdamarillo) {
        this.rdamarillo = rdamarillo;
    }

    public JRadioButton getRdrojo() {
        return rdrojo;
    }

    public void setRdrojo(JRadioButton rdrojo) {
        this.rdrojo = rdrojo;
    }

    public JRadioButton getRdverde() {
        return rdverde;
    }

    public void setRdverde(JRadioButton rdverde) {
        this.rdverde = rdverde;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JPanel pn;
    private javax.swing.JRadioButton rdamarillo;
    private javax.swing.JRadioButton rdrojo;
    private javax.swing.JRadioButton rdverde;
    // End of variables declaration//GEN-END:variables
}
